/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyFooter {
    }
    interface MyHeadline {
        "articleH": string;
        "nameH": string;
    }
    interface MyNav {
    }
    interface MySubheadline {
        "article": string;
        "name": string;
    }
    interface MyText {
        /**
          * The first name
         */
        "content": string;
    }
    interface MyWelcometext {
        "content": string;
    }
    interface TestComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFooterElement extends Components.MyFooter, HTMLStencilElement {
    }
    var HTMLMyFooterElement: {
        prototype: HTMLMyFooterElement;
        new (): HTMLMyFooterElement;
    };
    interface HTMLMyHeadlineElement extends Components.MyHeadline, HTMLStencilElement {
    }
    var HTMLMyHeadlineElement: {
        prototype: HTMLMyHeadlineElement;
        new (): HTMLMyHeadlineElement;
    };
    interface HTMLMyNavElement extends Components.MyNav, HTMLStencilElement {
    }
    var HTMLMyNavElement: {
        prototype: HTMLMyNavElement;
        new (): HTMLMyNavElement;
    };
    interface HTMLMySubheadlineElement extends Components.MySubheadline, HTMLStencilElement {
    }
    var HTMLMySubheadlineElement: {
        prototype: HTMLMySubheadlineElement;
        new (): HTMLMySubheadlineElement;
    };
    interface HTMLMyTextElement extends Components.MyText, HTMLStencilElement {
    }
    var HTMLMyTextElement: {
        prototype: HTMLMyTextElement;
        new (): HTMLMyTextElement;
    };
    interface HTMLMyWelcometextElement extends Components.MyWelcometext, HTMLStencilElement {
    }
    var HTMLMyWelcometextElement: {
        prototype: HTMLMyWelcometextElement;
        new (): HTMLMyWelcometextElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-footer": HTMLMyFooterElement;
        "my-headline": HTMLMyHeadlineElement;
        "my-nav": HTMLMyNavElement;
        "my-subheadline": HTMLMySubheadlineElement;
        "my-text": HTMLMyTextElement;
        "my-welcometext": HTMLMyWelcometextElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyFooter {
    }
    interface MyHeadline {
        "articleH"?: string;
        "nameH"?: string;
    }
    interface MyNav {
    }
    interface MySubheadline {
        "article"?: string;
        "name"?: string;
    }
    interface MyText {
        /**
          * The first name
         */
        "content"?: string;
    }
    interface MyWelcometext {
        "content"?: string;
    }
    interface TestComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-footer": MyFooter;
        "my-headline": MyHeadline;
        "my-nav": MyNav;
        "my-subheadline": MySubheadline;
        "my-text": MyText;
        "my-welcometext": MyWelcometext;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-footer": LocalJSX.MyFooter & JSXBase.HTMLAttributes<HTMLMyFooterElement>;
            "my-headline": LocalJSX.MyHeadline & JSXBase.HTMLAttributes<HTMLMyHeadlineElement>;
            "my-nav": LocalJSX.MyNav & JSXBase.HTMLAttributes<HTMLMyNavElement>;
            "my-subheadline": LocalJSX.MySubheadline & JSXBase.HTMLAttributes<HTMLMySubheadlineElement>;
            "my-text": LocalJSX.MyText & JSXBase.HTMLAttributes<HTMLMyTextElement>;
            "my-welcometext": LocalJSX.MyWelcometext & JSXBase.HTMLAttributes<HTMLMyWelcometextElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
